CREATE DATABASE INARI;
USE bd_awos_gonosc221;

CREATE TABLE USUARIOS (
    ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(50),
    CONTRASEÑA VARCHAR(50),
    ESTATUS INT,
    PERFIL INT,
    SESION INT
);

INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASEÑA) VALUES (
    'Oscar', 'oscargonzales98086@gmail.com', '1234567890'
);


-- Drop database
DROP DATABASE INARI;